### ISSUE TITLE
Add wireframe boxes like in BigDataViewer

### ISSUE THREAD

**Issue by Buglakova** [platybrowser/mmb-fiji#807]
It's quite hard to orient in the dataset in the slice viewer. Since it is already BigDataViewer, would be convenient to have the same box schematic:
![image](https://user-images.githubusercontent.com/89460016/176391999-787a27af-69ec-4b41-8ace-ef9fe9ec0c8c.png)

**Comment by tischi** [comment]
We have disabled this box to make the view less cluttered.
But I could just enable it.
@constantinpape OK?

**Comment by constantinpape** [comment]
> We have disabled this box to make the view less cluttered.
> But I could just enable it.

Can we add a checkbox for it?

**Comment by tischi** [comment]
yes, in the Fiji Command.
Unf. afaik one cannot toggle it on and off currently.

**Comment by constantinpape** [comment]
ok, ten lert's try to rurn it on by default in MoBIE beta and see if it gets too cluttered

**Comment by constantinpape** [comment]
Or is there a way to toggle this on the fly, @tpietzsch?

**Comment by tpietzsch** [comment]
It can be toggled using https://github.com/bigdataviewer/bigdataviewer-core/blob/d6edacb661291ef5d6b78df1cd9a1b8045553052/src/main/java/bdv/util/Prefs.java#L81-L84

With [bigdataviewer-core-10.4.1](https://forum.image.sc/t/new-bigdataviewer-version-10-4-1/68818) it can be toggled in the UI (the "show minimap" checkbox).
<img width="1024" alt="1d8bad9613965e71fef75d629b38e402364d7014" src="https://user-images.githubusercontent.com/622070/176465921-5b5a1ba6-d7e6-4a30-a8fb-d00cf0f521df.png">

**Comment by tischi** [comment]
I think I will then just enable it.
And wait for "merging" bdv-10.4.1 for having a UI option to toggle this on and off.
OK?

@tpietzsch will there also be a Java API for toggling the scale bar for one BDV instance on and off (I think `Prefs` did it globally for all instances)?

If yes, then bdv-10.4.1. would also fix https://github.com/mobie/mobie-viewer-fiji/issues/717

**Comment by tpietzsch** [comment]
It is planned to be able to toggle it for each instance, however that hasn't beed done in bdv-10.4.1 yet.

Currently, every BDV window can have a separate `AppearanceManager`, but they all forward to the same global `Prefs` which then actually control the overlay rendering. https://github.com/bigdataviewer/bigdataviewer-core/blob/4164f6addcba90156c9f1e17502610c49bc9867b/src/main/java/bdv/ui/appearance/AppearanceManager.java#L169-L197 (the `AppearanceManager.toPrefs()` and `fromPrefs()` methods are preemptively deprecated. Eventually we want to get rid of global `Prefs`.)

It is not clear to me yet, how it should work in the UI then. Probably it would be set up so that there is a (semi-)global `AppearanceManager` which is fed by the Preferences... dialog, and this has the defaults set by the user. This could then be wrapped, per window, in another `AppearanceManager` where the user-specified defaults can be overridden (partially) for each window. (E.g. by adding a shortcut to toggle the scale bar overlay)

**Comment by constantinpape** [comment]
More requests for this feature on the forum: https://forum.image.sc/t/overview-like-in-bigdataviewer/70081/2

So I think we should go ahead and activate this now, and once it's easily possible in BDV make it configurable.

**Comment by tischi** [comment]
Done.

**Comment by tischi** [comment]
(in MoBIE-beta)
