### ISSUE TITLE
CustomBrowser doesn't see additional tables from github

### ISSUE THREAD

**Issue by vzinche** [platybrowser/mmb-fiji#90]
When I'm using [my github branch](https://github.com/vzinche/platybrowser-backend/tree/master/data) as a table location and I try to add an additional table, it doesn't seem to see the [additional table](https://github.com/vzinche/platybrowser-backend/blob/master/data/1.0.1/tables/sbem-6dpf-1-whole-segmented-cells/cell_type_training_set.csv) that I've added.

However, when I specify the local folder that contains the very same files, it can see this table.

**Comment by tischi** [comment]
You have to add the table name to this file:

https://github.com/vzinche/platybrowser-backend/blob/master/data/1.0.1/tables/sbem-6dpf-1-whole-segmented-cells/additional_tables.txt

Locally, it works because I seem not to rely on this file, but look for all files in the folder (inconsistency, I admit).

**Comment by constantinpape** [comment]
@tischi we should also use the filesystem / github API for this and then get rid of the `additional_tables.txt`.

**Comment by tischi** [comment]
yes: https://github.com/platybrowser/mmb-fiji/issues/91
